# Server (IMPORTANT for Render)
server.port=${PORT:8080}

# Disable DB for now (so app runs without crash)
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=my-super-secret-key-for-mental-support-project-2026
app.jwt.expiration-ms=604800000

# CORS (update after Vercel deploy)
app.cors.allowed-origins=*
